### ISSUE TITLE
Migration fails with PrivateKeyWalletSubprovider used

### ISSUE THREAD

**Issue by lumir-mrkva** [0xProject/0x-monorepo#1120]
I am trying to deploy 0x to private sidechain, so I had to fiddle with [migrate.ts](https://github.com/0xProject/0x-monorepo/blob/development/packages/migrations/src/migrate.ts) a bit (you could make some script for it :wink:).

I replaced default provider in migrate.ts with PrivateKeyWalletSubprovider and RpcSubprovider
```
case ContractVersions.V2:
           const providerEngine = new Web3ProviderEngine();
           providerEngine.addProvider(new PrivateKeyWalletSubprovider('4b1eee2d827ce27f2c5f527da6637c43e42760aedfe52b3cd8e7173f18ab4341'));
           providerEngine.addProvider(new RPCSubprovider('http://localhost:7545'));
           providerEngine.start();
           txDefaults = {
               from: "0x0209f248982c7a9168bd794f7ee4645202dc9dd1"
           };
           await runV2MigrationsAsync(providerEngine, artifactsDir, txDefaults);
           break;
```
(this configuration is for a vannila ganache)

## Expected Behavior

`yarn migrate:v2` runs successfully

## Current Behavior

```
$ node ./lib/migrate.js --contracts-version 2.0.0
transactionHash: 0x2cd40e45f5ab17661f4bace28152e6d87fba31e9e8865c377c0118f2b3ae4737
ERC20Proxy successfully deployed at 0xc00329a5b3dfeeeb7d427632fcf22ec4483274ca
transactionHash: 0x833ce7824e687a66d7e0a89534624070b63eb48e1ff02f130de76105ff15f5d3
ERC721Proxy successfully deployed at 0xa9e584a3cc276f8d49430801f2f77d37d804e5f1
transactionHash: 0x41abad95f45b27225fc32483fdd5347c4c854be982c5f84cb57d5d34b16935cc
ZRXToken successfully deployed at 0x6b31305380b11ce4f6efb5ebdaeb08fb24eb12a3
transactionHash: 0x58e55def2aaf5483b4337cc6a7d9791efad7090e635baa8a6c5f9e48dd078a61
WETH9 successfully deployed at 0x1a2380be5789570e2930b9675cf38bcf6894b0f8
transactionHash: 0x7bc4e734947934c3fd93416767e195212c90c07a13a5d474a1788b8952941d3d
Exchange successfully deployed at 0x5625531c325a3739cd0b9d60e52356c75d951a9c
{ Error: invalid constructor argument (arg="_owners", reason="invalid address", value=undefined)
    at Object.throwError (/Users/mrq/git/0x-monorepo/node_modules/ethers/utils/errors.js:74:17)
    at _DeployDescription.encode (/Users/mrq/git/0x-monorepo/node_modules/ethers/contracts/interface.js:64:20)
    at Function.<anonymous> (/Users/mrq/git/0x-monorepo/packages/migrations/lib/2.0.0/contract_wrappers/asset_proxy_owner.js:1783:45)
    at step (/Users/mrq/git/0x-monorepo/packages/migrations/lib/2.0.0/contract_wrappers/asset_proxy_owner.js:56:23)
    at Object.next (/Users/mrq/git/0x-monorepo/packages/migrations/lib/2.0.0/contract_wrappers/asset_proxy_owner.js:37:53)
    at /Users/mrq/git/0x-monorepo/packages/migrations/lib/2.0.0/contract_wrappers/asset_proxy_owner.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/mrq/git/0x-monorepo/packages/migrations/lib/2.0.0/contract_wrappers/asset_proxy_owner.js:27:12)
    at Function.AssetProxyOwnerContract.deployAsync (/Users/mrq/git/0x-monorepo/packages/migrations/lib/2.0.0/contract_wrappers/asset_proxy_owner.js:1770:16)
    at Function.<anonymous> (/Users/mrq/git/0x-monorepo/packages/migrations/lib/2.0.0/contract_wrappers/asset_proxy_owner.js:1765:63)
    at step (/Users/mrq/git/0x-monorepo/packages/migrations/lib/2.0.0/contract_wrappers/asset_proxy_owner.js:56:23)
    at Object.next (/Users/mrq/git/0x-monorepo/packages/migrations/lib/2.0.0/contract_wrappers/asset_proxy_owner.js:37:53)
    at /Users/mrq/git/0x-monorepo/packages/migrations/lib/2.0.0/contract_wrappers/asset_proxy_owner.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/mrq/git/0x-monorepo/packages/migrations/lib/2.0.0/contract_wrappers/asset_proxy_owner.js:27:12)
    at Function.AssetProxyOwnerContract.deployFrom0xArtifactAsync (/Users/mrq/git/0x-monorepo/packages/migrations/lib/2.0.0/contract_wrappers/asset_proxy_owner.js:1757:16)
    at Object.<anonymous> (/Users/mrq/git/0x-monorepo/packages/migrations/lib/2.0.0/migration.js:111:82)
    at step (/Users/mrq/git/0x-monorepo/packages/migrations/lib/2.0.0/migration.js:32:23)
    at Object.next (/Users/mrq/git/0x-monorepo/packages/migrations/lib/2.0.0/migration.js:13:53)
    at fulfilled (/Users/mrq/git/0x-monorepo/packages/migrations/lib/2.0.0/migration.js:4:58)
    at <anonymous>
  reason: 'invalid address',
  code: 'INVALID_ARGUMENT',
  arg: '_owners',
  value: undefined }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "script:migrate:v2" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Workaround

When I used Mnemonic subprovider instead, it worked as expected.

**Comment by dekz** [comment]
Ah thanks for reporting.

Looks like our migration wants to set the `owners` to the first two accounts found in the provider. Since the `PrivateKeyWallet` only has one address this will fail.

**Comment by fabioberger** [comment]
Won't fix.
