### ISSUE TITLE
Unable to guess arg type

### ISSUE THREAD

**Issue by DamianRavi** [0xProject/0x-monorepo#1124]
Running contractWrappers.exchange.validateFillOrderThrowIfInvalidAsync() gives the following error for me. This is the value for makerAssetAmount which is in bigNumber format.

Error: Unable to guess arg type: 15000000000000000
    at /var/www/html/relayer/node_modules/@0xproject/order-utils/lib/src/crypto.js:47:23
    at arrayEach (/var/www/html/relayer/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/var/www/html/relayer/node_modules/lodash/lodash.js:9344:14)
    at Object._solHash (/var/www/html/relayer/node_modules/@0xproject/order-utils/lib/src/crypto.js:24:11)
    at Object.solSHA3 (/var/www/html/relayer/node_modules/@0xproject/order-utils/lib/src/crypto.js:17:31)
    at Object.structHash (/var/www/html/relayer/node_modules/@0xproject/order-utils/lib/src/eip712_utils.js:99:42)
    at Object.getOrderHashBuffer (/var/www/html/relayer/node_modules/@0xproject/order-utils/lib/src/order_hash.js:68:62)
    at Object.getOrderHashHex (/var/www/html/relayer/node_modules/@0xproject/order-utils/lib/src/order_hash.js:58:52)
    at OrderValidationUtils.<anonymous> (/var/www/html/relayer/node_modules/@0xproject/order-utils/lib/src/order_validation_utils.js:184:65)
    at step (/var/www/html/relayer/node_modules/@0xproject/order-utils/lib/src/order_validation_utils.js:32:23)
    at Object.next (/var/www/html/relayer/node_modules/@0xproject/order-utils/lib/src/order_validation_utils.js:13:53)
    at /var/www/html/relayer/node_modules/@0xproject/order-utils/lib/src/order_validation_utils.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/var/www/html/relayer/node_modules/@0xproject/order-utils/lib/src/order_validation_utils.js:3:12)
    at OrderValidationUtils.validateFillOrderThrowIfInvalidAsync (/var/www/html/relayer/node_modules/@0xproject/order-utils/lib/src/order_validation_utils.js:173:16)
    at ExchangeWrapper.<anonymous> (/var/www/html/relayer/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/exchange_wrapper.js:1357:67)
    at step (/var/www/html/relayer/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/exchange_wrapper.js:51:23)
    at Object.next (/var/www/html/relayer/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/exchange_wrapper.js:32:53)
    at /var/www/html/relayer/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/exchange_wrapper.js:26:71
    at new Promise (<anonymous>)
    at __awaiter (/var/www/html/relayer/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/exchange_wrapper.js:22:12)
    at ExchangeWrapper.validateFillOrderThrowIfInvalidAsync (/var/www/html/relayer/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/exchange_wrapper.js:1347:16)

**Comment by DamianRavi** [comment]
Using the standard bigNumber.js and not ZeroX.BigNumber is probably a bad idea.
