### ISSUE TITLE
[order-watcher] Exception UnhandledPromiseRejectionWarning getDependentOrderHashesByMaker

### ISSUE THREAD

**Issue by amaurer** [0xProject/0x-monorepo#1130]
## Current Behavior

I get a periodic error in my OrderWatcher instance. I really don't have a lot of information for you but the error, but I thought I'd add it just in case someone else runs into it.
```
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.from (native)
    at DependentOrderHashesTracker.getDependentOrderHashesByMaker (/opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/dependent_order_hashes_tracker.js:47:42)
    at OrderWatcher.<anonymous> (/opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/order_watcher.js:401:73)
    at step (/opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/order_watcher.js:43:23)
    at Object.next (/opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/order_watcher.js:24:53)
    at /opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/order_watcher.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/order_watcher.js:14:12)
    at OrderWatcher._onEventWatcherCallbackAsync (/opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/order_watcher.js:275:16)
    at EventWatcher.<anonymous> (/opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/event_watcher.js:213:21)
    at step (/opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/event_watcher.js:43:23)
    at Object.next (/opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/event_watcher.js:24:53)
    at /opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/event_watcher.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/event_watcher.js:14:12)
    at EventWatcher._emitDifferencesAsync (/opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/event_watcher.js:208:16)
    at EventWatcher.<anonymous> (/opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/event_watcher.js:176:51)
    at step (/opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/event_watcher.js:43:23)
    at Object.next (/opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/event_watcher.js:24:53)
    at /opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/event_watcher.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/node_modules/@0xproject/order-watcher/lib/src/order_watcher/event_watcher.js:14:12)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
```
The instance is watching 5 orders.

I have my addOrderAsync functions assigned a catch block which it is not executing. This is some internal exception error that doesn't cause the process to exit.

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 1.0.8  |
|             `geth` | 1.8.17  |
| Network |
| ------- |
| mainnet    |

**Comment by fabioberger** [comment]
Thanks for the report @kgh2927845, will set time aside to fix both these issues soon.

**Comment by coinpennant** [comment]
Hi. Any progress about the fix?

**Comment by fabioberger** [comment]
@coinpennant this has been slated for the next sprint.

**Comment by MichaelDragan** [comment]
Hey, was just wondering if there's been any progress about this fix.

**Comment by fabioberger** [comment]
@LogvinovLeon is currently working on a fix. You should see a PR up by EOD tomorrow.

**Comment by WyseNynja** [comment]
I just ran into this. Glad to see a PR is already on the way

**Comment by amaurer** [comment]
Yes, working with it now and looks good so far. Thank you!
