### ISSUE TITLE
OrderWatch Bug: UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object or Error: Failed to fetch parent block.

### ISSUE THREAD

**Issue by coinpennant** [0xProject/0x-monorepo#1172]
## Expected Behavior

Should run in infura mainnet.

## Current Behavior

C:\Users\mitja\Downloads\order-watch2>node ./dist/main.js
```
start
end 2
6551584
1
end

{ code: -32000, message: 'unknown block' }
{ code: -32000, message: 'unknown block' }
{ code: -32000, message: 'unknown block' }
Error: Failed to fetch parent block.
    at Object.<anonymous> (C:\Users\mitja\Downloads\order-watch2\node_modules\ethereumjs-blockstream\output\source\block-reconciler.js:106:27)
    at step (C:\Users\mitja\Downloads\order-watch2\node_modules\ethereumjs-blockstream\output\source\block-reconciler.js:32:23)
    at Object.next (C:\Users\mitja\Downloads\order-watch2\node_modules\ethereumjs-blockstream\output\source\block-reconciler.js:13:53)
    at fulfilled (C:\Users\mitja\Downloads\order-watch2\node_modules\ethereumjs-blockstream\output\source\block-reconciler.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)


(node:16972) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.from (native)
    at DependentOrderHashesTracker.getDependentOrderHashesByMaker (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\dependent_order_hashes_tracker.js:47:42)
    at OrderWatcher.<anonymous> (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\order_watcher.js:401:73)
    at step (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\order_watcher.js:43:23)
    at Object.next (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\order_watcher.js:24:53)
    at C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\order_watcher.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\order_watcher.js:14:12)
    at OrderWatcher._onEventWatcherCallbackAsync (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\order_watcher.js:275:16)
    at EventWatcher.<anonymous> (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:213:21)
    at step (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:43:23)
    at Object.next (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:24:53)
    at C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:14:12)
    at EventWatcher._emitDifferencesAsync (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:208:16)
    at EventWatcher.<anonymous> (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:176:51)
    at step (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:43:23)
    at Object.next (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:24:53)
    at C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:14:12)
(node:16972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ code: -32000, message: 'unknown block' }
{ code: -32000, message: 'unknown block' }
{ code: -32000, message: 'unknown block' }
{ code: -32000, message: 'unknown block' }
(node:16972) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.from (native)
    at DependentOrderHashesTracker.getDependentOrderHashesByMaker (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\dependent_order_hashes_tracker.js:47:42)
    at OrderWatcher.<anonymous> (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\order_watcher.js:401:73)
    at step (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\order_watcher.js:43:23)
    at Object.next (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\order_watcher.js:24:53)
    at C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\order_watcher.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\order_watcher.js:14:12)
    at OrderWatcher._onEventWatcherCallbackAsync (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\order_watcher.js:275:16)
    at EventWatcher.<anonymous> (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:213:21)
    at step (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:43:23)
    at Object.next (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:24:53)
    at C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:14:12)
    at EventWatcher._emitDifferencesAsync (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:208:16)
    at EventWatcher.<anonymous> (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:176:51)
    at step (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:43:23)
    at Object.next (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:24:53)
    at C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\mitja\Downloads\order-watch2\node_modules\@0xproject\order-watcher\lib\src\order_watcher\event_watcher.js:14:12)
(node:16972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
{ code: -32000, message: 'unknown block' }
Error: Failed to fetch parent block.
    at Object.<anonymous> (C:\Users\mitja\Downloads\order-watch2\node_modules\ethereumjs-blockstream\output\source\block-reconciler.js:106:27)
    at step (C:\Users\mitja\Downloads\order-watch2\node_modules\ethereumjs-blockstream\output\source\block-reconciler.js:32:23)
    at Object.next (C:\Users\mitja\Downloads\order-watch2\node_modules\ethereumjs-blockstream\output\source\block-reconciler.js:13:53)
    at fulfilled (C:\Users\mitja\Downloads\order-watch2\node_modules\ethereumjs-blockstream\output\source\block-reconciler.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:16972) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.from (native)
```

## Steps to Reproduce (for bugs)

```
1. npm install
2. tsc
3. node ./dist/main.js
```

main.ts

```
import { OrderWatcher, OnOrderStateChangeCallback, OrderWatcherConfig } from '@0xproject/order-watcher';
import { SignerSubprovider, RPCSubprovider, Web3ProviderEngine } from '@0xproject/subproviders';
import { Web3Wrapper } from '@0xproject/web3-wrapper';

let url = 'https://mainnet.infura.io/0a8359dc4ae54b7c9406bb0b09422afe';
//let url = 'http://localhost:8545';
let provider = new RPCSubprovider(url);
const providerEngine = new Web3ProviderEngine();
providerEngine.addProvider(provider);
providerEngine.start();

let orderWatcher = null;

function delay(milliseconds: number, count: number): Promise<number> {
    return new Promise<number>(resolve => {
            setTimeout(() => {
                resolve(count);
            }, milliseconds);
        });
}

async function app() {
    console.log('start');     

        // Get all of the accounts through the Web3Wrapper
        const web3Wrapper = new Web3Wrapper(providerEngine);
        const blockNumber = await web3Wrapper.getBlockNumberAsync();
        const networkId = await web3Wrapper.getNetworkIdAsync();
        
        console.log(blockNumber);
        console.log(networkId);

        //let networkId = 1;
        //let partialConfig = new Partial<OrderWatcherConfig>();

        orderWatcher = new OrderWatcher(
        web3Wrapper.getProvider(), 
        networkId
        );

        //  orderWatcher.subscribe(
        //     ( error: Error|null, orderState?: OrderState ) : void => {
        //         console.log('callback');
        //         console.log(error);
        //         console.log(orderState);

        //     }
        //  );

        orderWatcher.subscribe(
            ( callback: OnOrderStateChangeCallback ) : void => {
                console.log('callback');
                //console.log(callback);
            }
        );    

        // for (let i = 0; i < 20; i++) {
        //     // await is converting Promise<number> into number
        //     const count:number = await delay(1000, i);
        //     console.log(count);
        // }
        
        console.log('end');     
}

app()

const waitUntil = require('async-wait-until');
 
const timeOfStart = Date.now();

waitUntil(() => {
    const timePassed = Date.now() - timeOfStart;
   
    return false;        
}, 5 * 60 * 10000)
  .then((result) => {
    // Here are the operations to be done after predicate
    console.log('Async operation succeeded, predicate result = ', result);
  })
  .catch((error) => {
    // Here are the operations to be done if predicate didn't succeed in the timeout
    console.log('Async operation failed: ', error);
  });

console.log('end 2');

```

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 2  |

| Network |
| ------- |
| mainnet |

**Comment by coinpennant** [comment]
Same as
https://github.com/0xProject/0x-monorepo/issues/1130

**Comment by fabioberger** [comment]
Closing as duplicate
