### ISSUE TITLE
Erc721Token getLogsAsync cannot handle _tokenId as a BigNumber

### ISSUE THREAD

**Issue by dwbauschlicher** [0xProject/0x-monorepo#1534]
A Bug occurs when calling getLogsAsync with IndexFilterValues, where `_tokenId` is a `BigNumber`.

```typescript
 contractWrappers.erc721Token.getLogsAsync(,,, { _tokenId: aTokenId })
```

When aTokenId is a BigNumber, an error with message 'Error: invalid type' is thrown. 

```
Error: invalid type
    at Object.exports.toBuffer (/Users/jacob/projects/ethdev/0x/0x-starter-project/node_modules/ethereumjs-util/dist/index.js:183:13)
    at Object.getTopicsForIndexedArgs (/Users/jacob/projects/ethdev/0x/0x-starter-project/node_modules/@0x/contract-wrappers/src/utils/filter_utils.ts:55:40)
    at Object.getFilter (/Users/jacob/projects/ethdev/0x/0x-starter-project/node_modules/@0x/contract-wrappers/src/utils/filter_utils.ts:25:50)
    at ERC721TokenWrapper.<anonymous> (/Users/jacob/projects/ethdev/0x/0x-starter-project/node_modules/@0x/contract-wrappers/src/contract_wrappers/contract_wrapper.ts:102:36)
```

When aTokenId is a string, no matching event logs are found.

The error may be due to BigNumber inconsistencies in 0x.js and ethereumjs-utils.

Workaround is to convert the tokenId to a hex string.

```typescript
    const logs = await contractWrappers.erc721Token.getLogsAsync<ERC721TokenTransferEventArgs>(
        dummyERC721TokenContract.address,
        ERC721TokenEvents.Transfer,
        { fromBlock: 1, toBlock: 1000 },
        { _tokenId: `0x${tokenId.toString(16)}` },
    );
```
 
`getLogsAsync` should support `BigNumber` as that is the consistent type when interacting with the wrapper.

**Comment by dekz** [comment]
ethereumjs-utils is able to handle BN but doesn't appear to handle BigNumber.js. 


```javascript
// ethereumjs-util/dist/index.js
exports.toBuffer = function (v) {
  if (!Buffer.isBuffer(v)) {
    if (Array.isArray(v)) {
      v = Buffer.from(v);
    } else if (typeof v === 'string') {
      if (exports.isHexString(v)) {
        v = Buffer.from(exports.padToEven(exports.stripHexPrefix(v)), 'hex');
      } else {
        v = Buffer.from(v);
      }
    } else if (typeof v === 'number') {
      v = exports.intToBuffer(v);
    } else if (v === null || v === undefined) {
      v = Buffer.allocUnsafe(0);
    } else if (BN.isBN(v)) {
      v = v.toArrayLike(Buffer);
    } else if (v.toArray) {
      // converts a BN to a Buffer
      v = Buffer.from(v.toArray());
    } else {
      throw new Error('invalid type');
    }
  }
  return v;
};
```

Our filter utils is attempting to turn the value into a buffer:

```typescript
// filter_utils.ts
    getTopicsForIndexedArgs(abi: EventAbi, indexFilterValues: IndexedFilterValues): Array<string | null> {
        const topics: Array<string | null> = [];
        for (const eventInput of abi.inputs) {
            if (!eventInput.indexed) {
                continue;
            }
            if (_.isUndefined(indexFilterValues[eventInput.name])) {
                // Null is a wildcard topic in a JSON-RPC call
                topics.push(null);
            } else {
                const value = indexFilterValues[eventInput.name] as string;
                const buffer = ethUtil.toBuffer(value);
                const paddedBuffer = ethUtil.setLengthLeft(buffer, TOPIC_LENGTH);
                const topic = ethUtil.bufferToHex(paddedBuffer);
                topics.push(topic);
            }
        }
        return topics;
    },
```

I believe we have plans to get on a consistent big number library

**Comment by fabioberger** [comment]
@dekz we've updated to the latest version of BigNumber across our tooling. I'd also be in favor of just throwing a more helpful error message and force the end-developer to convert to hex. Thoughts?
