### ISSUE TITLE
ERC721 order watcher type error

### ISSUE THREAD

**Issue by dwbauschlicher** [0xProject/0x-monorepo#1550]
Using the orderwatcher to watch an erc721 I sometimes get an error. 
The ERC20 token watcher never gives this.

In this log the 0xa5e5be69c923c701ae6ac8f1f5936af3ae610c68 is the token that I am watching.
here is the log:
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0xa5e5be69c923c701ae6ac8f1f5936af3ae610c68' of undefined
warning.js:18
    at DependentOrderHashesTracker.getDependentOrderHashesByERC721ByMaker (c:\apps\apps\GodsUnchained\gudecks\backend\orderWatcher\node_modules@0x\order-watcher\src\order_watcher\dependent_order_hashes_tracker.ts:41:82)
    at OrderWatcher.<anonymous> (c:\apps\apps\GodsUnchained\gudecks\backend\orderWatcher\node_modules@0x\order-watcher\src\order_watcher\order_watcher.ts:400:71)
    at step (c:\apps\apps\GodsUnchained\gudecks\backend\orderWatcher\node_modules@0x\order-watcher\lib\src\order_watcher\order_watcher.js:43:23)
    at Object.next (c:\apps\apps\GodsUnchained\gudecks\backend\orderWatcher\node_modules@0x\order-watcher\lib\src\order_watcher\order_watcher.js:24:53)
    at c:\apps\apps\GodsUnchained\gudecks\backend\orderWatcher\node_modules@0x\order-watcher\lib\src\order_watcher\order_watcher.js:18:71
```
0xa5e5be69c923c701ae6ac8f1f5936af3ae610c68 is the address of the erc721 contract

**Comment by dwbauschlicher** [comment]
Is there any update on this issue? It still pops up frequently with many different erc721 orders.
