### ISSUE TITLE
python - web3 tuple support

### ISSUE THREAD

**Issue by benjyz** [0xProject/0x-monorepo#1590]
after pip3 install 0x-web3 I get the following issue. not sure if I need some new requirements for the web3 fork.

```
>>> import web3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/web3/__init__.py", line 17, in <module>
    from web3.main import Web3  # noqa: E402
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/web3/main.py", line 17, in <module>
    from web3._utils.abi import (
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/web3/_utils/abi.py", line 17, in <module>
    from eth_utils.abi import (
ImportError: cannot import name 'collapse_if_tuple' from 'eth_utils.abi' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/eth_utils/abi.py)
```

**Comment by benjyz** [comment]
tested with venv
```

$ py
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import web3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/web3/__init__.py", line 17, in <module>
    from web3.main import Web3  # noqa: E402
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/web3/main.py", line 17, in <module>
    from web3._utils.abi import (
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/web3/_utils/abi.py", line 17, in <module>
    from eth_utils.abi import (
ImportError: cannot import name 'collapse_if_tuple' from 'eth_utils.abi' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/eth_utils/abi.py)
```

**Comment by feuGeneA** [comment]
That error message is an indication that you're mixing web3 releases.

From our discussion on [Discord](https://discord.gg/FRSCbMZ) #python:

> do you really need to be on that cutting edge of web3.py?
> there are two versions of 0x-web3 published to PyPI.
> one goes with the latest (pre-release, 5.x) version of web3.py.
> another goes with the latest stable version of web3.py (4.8.2).
> https://pypi.org/project/0x-web3/#history
> note the pre-release and the stable release. you'll get stable if you don't specify.
> i've merged it both places, so you can use whichever you want.
> but of course you have to line them up, can't mix them.
