### ISSUE TITLE
python: exchange test contract deploy

### ISSUE THREAD

**Issue by benjyz** [0xProject/0x-monorepo#1600]
not sure, but the exchange test assumes that the exchange contract is already deployed

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/web3/contract.py", line 1384, in call_contract_function
    output_data = decode_abi(output_types, return_data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/eth_abi/abi.py", line 96, in decode_abi
    return decoder(stream)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/eth_abi/decoding.py", line 118, in __call__
    return self.decode(stream)
  File "/Users/ben/0x/eth-utils/eth_utils/functional.py", line 46, in inner
    return callback(fn(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/eth_abi/decoding.py", line 164, in decode
    yield decoder(stream)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/eth_abi/decoding.py", line 118, in __call__
    return self.decode(stream)
  File "/Users/ben/0x/eth-utils/eth_utils/functional.py", line 46, in inner
    return callback(fn(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/eth_abi/decoding.py", line 164, in decode
    yield decoder(stream)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/eth_abi/decoding.py", line 118, in __call__
    return self.decode(stream)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/eth_abi/decoding.py", line 186, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/eth_abi/decoding.py", line 296, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "try_ordering.py", line 72, in <module>
    test_get_order_info()    
  File "try_ordering.py", line 54, in test_get_order_info
    order_info = OrderInfo(*exchange.call().getOrderInfo(order))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/web3/contract.py", line 1406, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?
```

**Comment by fabioberger** [comment]
@benjyz you can download a Ganache snapshot with the 0x contracts pre-deployed here: http://ganache-snapshots.0x.org.s3.amazonaws.com/0x_ganache_snapshot-2.4.0.zip. Run Ganache with the following flags:

```
ganache-cli --noVMErrorsOnRPCResponse --gasLimit 10000000  --db 0x_ganache_snapshot  -p 8545 --networkId 50 -m "concert load couple harbor equip island argue ramp clarify fence smart topic"
```

**Comment by feuGeneA** [comment]
From the `contract_demo` `README`:

> Tests depend on a running ganache instance with the 0x contracts deployed in it. For convenience, a docker container is provided that has ganache-cli and a snapshot containing the necessary contracts. A shortcut is provided to run that docker container: `./setup.py ganache`. With that running, the tests can be run with `./setup.py test`.
