### ISSUE TITLE
RevertTraceSubprovider isn't setting "error.reason"

### ISSUE THREAD

**Issue by WyseNynja** [0xProject/0x-monorepo#1664]
## Current Behavior

I have a test that looks something like this:
```
    try {
      await contractInstance.foobar(1);

      assert.fail("the above await was supposed to revert");
    } catch (error) {
      // if error.reason is undefined, this failed for some unexpected reason
      if (error.reason === undefined) {
        console.log("error.reason is undefined");
        console.log(error);
      }

      assert.equal(error.reason, "UNABLE_REPAY_ETH");
    }
```

When I run `truffle test`, everything passes

When I run `MODE=trace truffle test`, the test should still pass, but it fails. The logs have helpful output that includes the revert string, but it looks like RevertTraceSubprovider isn't storing it in `error.reason`

```
Stack trace for REVERT:

/usr/src/app/contracts-sol-compiler/Foobar.sol:176:8:
        require(address(this).balance >= borrow_wei, "UNABLE_REPAY_ETH")




Stack trace for REVERT:

/usr/src/app/contracts-sol-compiler/Foobar.sol:176:8:
        require(address(this).balance >= borrow_wei, "UNABLE_REPAY_ETH")


error.reason is undefined
Error: VM Exception while processing transaction: revert UNABLE_REPAY_ETH
    at WebsocketSubprovider._handleSocketMessage (/usr/src/app/node_modules/web3-provider-engine/subproviders/websocket.js:121:18)
    at WebSocket.onMessage (/usr/src/app/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:189:13)
    at Receiver.receiverOnMessage (/usr/src/app/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:189:13)
    at Receiver.dataMessage (/usr/src/app/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/usr/src/app/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/usr/src/app/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/usr/src/app/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Receiver.Writable.write (_stream_writable.js:294:11)
    at Socket.socketOnData (/usr/src/app/node_modules/ws/lib/websocket.js:795:35)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    1) ... should revert if trade isn't an arbitrage
    > No events were emitted
```

For now I'm going to wrap this check in a `if (global.mode != "trace") { ... }`. I could also parse the error text myself, but this feels like a bug.

## Steps to Reproduce (for bugs)

I can make a full repo with more info to reproduce if you need, but I think the example test above should be straight forward to test.

## Context

I'm trying to use the sol-coverage, sol-trace and sol-profile like in https://github.com/0xProject/dev-tools-truffle-example. Even with this test failing, sol-trace has been very helpful for debugging other things in my repo. I'd prefer not to add any branching to my tests since that can cause all sorts of problems.

## Your Environment

| Package | Version |
| ------: | :------ |
|             @0x/sol-trace | 2.0.7   |
|             @0x/sol-compiler | 3.1.2   |
|             @0x/sol-coverage | 2.0.6   |
|             @0x/sol-profiler | 3.1.1   |

**Comment by LogvinovLeon** [comment]
This is definitely a bug. To be honest - I will most probably not have time to look into that for the next couple of weeks because of other projects and aggressive deadlines, but if you would find time to submit a PR - I will review, merge and publish it.
