### ISSUE TITLE
sol-tracing-utils erring on contract using solidity 0.5.4 and "address payable"

### ISSUE THREAD

**Issue by WyseNynja** [0xProject/0x-monorepo#1671]
## Expected Behavior

`yarn coverage` (`MODE=coverage truffle test`) should run to completion without errors.

## Current Behavior

`yarn test` and `yarn trace` complete successfully. But when I run `yarn coverage`, my contracts compile and then I get this error:

```
{ Error
    at new ParserError (/usr/src/app/node_modules/@0x/sol-tracing-utils/node_modules/solidity-parser-antlr/dist/index.js:25:16)
    at Object.parse (/usr/src/app/node_modules/@0x/sol-tracing-utils/node_modules/solidity-parser-antlr/dist/index.js:71:11)
    at Object.exports.collectCoverageEntries (/usr/src/app/node_modules/@0x/sol-tracing-utils/src/collect_coverage_entries.ts:14:28)
    at CoverageSubprovider._coverageHandler (/usr/src/app/node_modules/@0x/sol-coverage/src/coverage_subprovider.ts:107:44)
    at /usr/src/app/node_modules/@0x/sol-tracing-utils/src/trace_collector.ts:108:53
    at /usr/src/app/node_modules/lodash/lodash.js:3549:27
    at /usr/src/app/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/usr/src/app/node_modules/lodash/lodash.js:2996:24)
    at /usr/src/app/node_modules/lodash/lodash.js:4880:18
    at baseMap (/usr/src/app/node_modules/lodash/lodash.js:3548:7)
    at Function.map (/usr/src/app/node_modules/lodash/lodash.js:9556:14)
    at TraceCollector.<anonymous> (/usr/src/app/node_modules/@0x/sol-tracing-utils/src/trace_collector.ts:107:11)
    at step (/usr/src/app/node_modules/@0x/sol-tracing-utils/lib/src/trace_collector.js:32:23)
    at Object.next (/usr/src/app/node_modules/@0x/sol-tracing-utils/lib/src/trace_collector.js:13:53)
    at fulfilled (/usr/src/app/node_modules/@0x/sol-tracing-utils/lib/src/trace_collector.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'ParserError',
  message:
   'extraneous input \'payable\' expecting {\',\', \')\'}. mismatched input \',\' expecting {\';\', \'{\', \'returns\'}. mismatched input \')\' expecting {\';\', \'=\'}. extraneous input \'{\' expecting {\'from\', \'constant\', \'internal\', \'private\', \'public\', Identifier}. mismatched input \'(\' expecting {\';\', \'=\'}. extraneous input \'(\' expecting {\'from\', \'constant\', \'internal\', \'private\', \'public\', Identifier}. mismatched input \',\' expecting {\';\', \'=\'}. mismatched input \')\' expecting {\'from\', \'constant\', \'internal\', \'private\', \'public\', Identifier}. extraneous input \'function\' expecting {<EOF>, \'pragma\', \'import\', \'contract\', \'interface\', \'library\'}',
  errors:
   [ { message: 'extraneous input \'payable\' expecting {\',\', \')\'}',
       line: 106,
       column: 52 },
     { message:
        'mismatched input \',\' expecting {\';\', \'{\', \'returns\'}',
       line: 106,
       column: 62 },
     { message: 'mismatched input \')\' expecting {\';\', \'=\'}',
       line: 106,
       column: 78 },
     { message:
        'extraneous input \'{\' expecting {\'from\', \'constant\', \'internal\', \'private\', \'public\', Identifier}',
       line: 106,
       column: 105 },
     { message: 'mismatched input \'(\' expecting {\';\', \'=\'}',
       line: 107,
       column: 15 },
     { message:
        'extraneous input \'(\' expecting {\'from\', \'constant\', \'internal\', \'private\', \'public\', Identifier}',
       line: 107,
       column: 39 },
     { message: 'mismatched input \',\' expecting {\';\', \'=\'}',
       line: 107,
       column: 42 },
     { message:
        'mismatched input \')\' expecting {\'from\', \'constant\', \'internal\', \'private\', \'public\', Identifier}',
       line: 107,
       column: 50 },
     { message:
        'extraneous input \'function\' expecting {<EOF>, \'pragma\', \'import\', \'contract\', \'interface\', \'library\'}',
       line: 110,
       column: 4 } ],
  stack:
   'Error\n    at new ParserError (/usr/src/app/node_modules/@0x/sol-tracing-utils/node_modules/solidity-parser-antlr/dist/index.js:25:16)\n    at Object.parse (/usr/src/app/node_modules/@0x/sol-tracing-utils/node_modules/solidity-parser-antlr/dist/index.js:71:11)\n    at Object.exports.collectCoverageEntries (/usr/src/app/node_modules/@0x/sol-tracing-utils/src/collect_coverage_entries.ts:14:28)\n    at CoverageSubprovider._coverageHandler (/usr/src/app/node_modules/@0x/sol-coverage/src/coverage_subprovider.ts:107:44)\n    at /usr/src/app/node_modules/@0x/sol-tracing-utils/src/trace_collector.ts:108:53\n    at /usr/src/app/node_modules/lodash/lodash.js:3549:27\n    at /usr/src/app/node_modules/lodash/lodash.js:4911:15\n    at baseForOwn (/usr/src/app/node_modules/lodash/lodash.js:2996:24)\n    at /usr/src/app/node_modules/lodash/lodash.js:4880:18\n    at baseMap (/usr/src/app/node_modules/lodash/lodash.js:3548:7)\n    at Function.map (/usr/src/app/node_modules/lodash/lodash.js:9556:14)\n    at TraceCollector.<anonymous> (/usr/src/app/node_modules/@0x/sol-tracing-utils/src/trace_collector.ts:107:11)\n    at step (/usr/src/app/node_modules/@0x/sol-tracing-utils/lib/src/trace_collector.js:32:23)\n    at Object.next (/usr/src/app/node_modules/@0x/sol-tracing-utils/lib/src/trace_collector.js:13:53)\n    at fulfilled (/usr/src/app/node_modules/@0x/sol-tracing-utils/lib/src/trace_collector.js:4:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
```

I didn't notice this on `yarn profile` because I only enabled profiling on a function that didn't use `address payable`

## Possible Solution

Update solidity-parser-antlr in @0x/sol-tracing-utils from 0.2.12 to a newer version. 0.4.1 is the latest release. According to https://github.com/federicobond/solidity-parser-antlr/blob/master/CHANGES.md 0.3.3 is when support for address payable was added.

## Steps to Reproduce (for bugs)

I think any solidity 0.5.4 contract with an `address payable` argument should trigger this.

## Context

sol-trace has been super helpful for me while developing my smart contract and I wanted to give sol-coverage a try.

## Your Environment

```
  "dependencies": {
    "@0x/sol-compiler": "^3.1.2",
    "mocha": "^6.0.1",
    "openzeppelin-solidity": "^2.1.3",
    "truffle": "^5.0.2"
  },
  "devDependencies": {
    "@0x/sol-coverage": "^3.0.0",
    "@0x/sol-trace": "^2.0.7",
    "@types/chai": "^4.1.7",
    "chai": "^4.2.0",
    "istanbul": "^0.4.5",
    "prettier": "^1.16",
    "prettier-plugin-solidity": "^1.0.0-alpha.18",
    "solhint": "^2.0.0",
    "web3-provider-engine": "^14.1.0"
  }
```

**Comment by LogvinovLeon** [comment]
New version published
