### ISSUE TITLE
sol-compiler: Getting list of Solc versions from Github gets rate-limited

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-monorepo#2236]
Everytime we compile a contract package using `@0x/sol-compiler`, we make a request to Github to fetch the latest versions of Solc available. As the size of the team has grown, we've been making more and more requests with a greater frequency. This has led to this request failing as we hit Github's rate-limit:

```
{ FetchError: response timeout at https://contracts/utils/ethereum.github.io/solc-bin/bin/soljson-v0.5.12+commit.7709ece9.js over limit: 20000
 |     at Timeout._onTimeout contracts/utils/(/Users/rickmorty/Documents/projects/0x/0x-monorepo/node_modules/node-fetch/lib/body.js:117:12)
 |     at listOnTimeout contracts/utils/(internal/timers.js:535:17)
 |     at processTimers contracts/utils/(internal/timers.js:479:7)
 |   name: 'FetchError',
 |   message:
 |    'response timeout at https://contracts/utils/ethereum.github.io/solc-bin/bin/soljson-v0.5.12+commit.7709ece9.js over limit: 20000',
 |   type: 'body-timeout' }
```

The list of versions does not update very often. We could easily cache the list in `website-backend` and only ping Github  with a much lower frequency. Let's add some sort of cache on these requests to stop getting rate-limited.

## Steps to Reproduce (for bugs)

```
1.
2.
3.
```

## Your Environment

| Package | Version |
| ------: | :------ |

| Network |
| ------- |
| NAME    |

**Comment by fabioberger** [comment]
Turns out there was a simpler solution which is to properly cache the solc versions we download locally. We were removing them every time which was causing us to hit the rate limit.
