### ISSUE TITLE
Extra space in `provider.send` signature in web3@1.2.1 causing errors

### ISSUE THREAD

**Issue by mrwillis** [0xProject/0x-monorepo#2285]
dev-utils@2.3.3

## Expected Behavior

`BlockchainLifecycle.startAsync()` should work

## Current Behavior

Returns error when doing (truffle tests, truffle@5.0.41)

web3@1.2.1

```typescript
  const web3wrapper = new Web3Wrapper(web3.currentProvider);
  const blockchainLifecycle = new BlockchainLifecycle(web3wrapper);
  const provider = new providers.Web3Provider(web3.currentProvider);
```

```
1) Contract: FillOrder
       "before all" hook:
     TypeError: Cannot read property 'then' of undefined
      at Object.provider.sendAsync (node_modules/@0x/utils/src/provider_utils.ts:91:14)
      at /home/julian/betx/betx-contracts/node_modules/@0x/utils/src/promisify.ts:15:24
      at new Promise (<anonymous>)
      at Object.<anonymous> (node_modules/@0x/utils/src/promisify.ts:11:16)
      at step (node_modules/@0x/utils/lib/src/promisify.js:32:23)
      at Object.next (node_modules/@0x/utils/lib/src/promisify.js:13:53)
      at /home/julian/betx/betx-contracts/node_modules/@0x/utils/lib/src/promisify.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/@0x/utils/lib/src/promisify.js:3:12)
      at promisifiedFunction (node_modules/@0x/utils/lib/src/promisify.js:71:16)
      at Web3Wrapper.<anonymous> (node_modules/@0x/web3-wrapper/src/web3_wrapper.ts:679:76)
      at step (node_modules/@0x/web3-wrapper/lib/src/web3_wrapper.js:43:23)
      at Object.next (node_modules/@0x/web3-wrapper/lib/src/web3_wrapper.js:24:53)
      at /home/julian/betx/betx-contracts/node_modules/@0x/web3-wrapper/lib/src/web3_wrapper.js:18:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/@0x/web3-wrapper/lib/src/web3_wrapper.js:14:12)
      at Web3Wrapper.sendRawPayloadAsync (node_modules/@0x/web3-wrapper/lib/src/web3_wrapper.js:926:16)
      at Web3Wrapper.<anonymous> (node_modules/@0x/web3-wrapper/src/web3_wrapper.ts:200:40)
      at step (node_modules/@0x/web3-wrapper/lib/src/web3_wrapper.js:43:23)
      at Object.next (node_modules/@0x/web3-wrapper/lib/src/web3_wrapper.js:24:53)
      at /home/julian/betx/betx-contracts/node_modules/@0x/web3-wrapper/lib/src/web3_wrapper.js:18:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/@0x/web3-wrapper/lib/src/web3_wrapper.js:14:12)
      at Web3Wrapper.getNodeVersionAsync (node_modules/@0x/web3-wrapper/lib/src/web3_wrapper.js:228:16)
      at Web3Wrapper.<anonymous> (node_modules/@0x/web3-wrapper/src/web3_wrapper.ts:691:36)
      at step (node_modules/@0x/web3-wrapper/lib/src/web3_wrapper.js:43:23)
      at Object.next (node_modules/@0x/web3-wrapper/lib/src/web3_wrapper.js:24:53)
      at /home/julian/betx/betx-contracts/node_modules/@0x/web3-wrapper/lib/src/web3_wrapper.js:18:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/@0x/web3-wrapper/lib/src/web3_wrapper.js:14:12)
      at Web3Wrapper.getNodeTypeAsync (node_modules/@0x/web3-wrapper/lib/src/web3_wrapper.js:950:16)
      at BlockchainLifecycle.<anonymous> (node_modules/@0x/dev-utils/src/blockchain_lifecycle.ts:76:54)
      at step (node_modules/@0x/dev-utils/lib/src/blockchain_lifecycle.js:32:23)
      at Object.next (node_modules/@0x/dev-utils/lib/src/blockchain_lifecycle.js:13:53)
      at /home/julian/betx/betx-contracts/node_modules/@0x/dev-utils/lib/src/blockchain_lifecycle.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/@0x/dev-utils/lib/src/blockchain_lifecycle.js:3:12)
      at BlockchainLifecycle._getNodeTypeAsync (node_modules/@0x/dev-utils/lib/src/blockchain_lifecycle.js:166:16)
      at BlockchainLifecycle.<anonymous> (node_modules/@0x/dev-utils/src/blockchain_lifecycle.ts:22:37)
      at step (node_modules/@0x/dev-utils/lib/src/blockchain_lifecycle.js:32:23)
      at Object.next (node_modules/@0x/dev-utils/lib/src/blockchain_lifecycle.js:13:53)
      at /home/julian/betx/betx-contracts/node_modules/@0x/dev-utils/lib/src/blockchain_lifecycle.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/@0x/dev-utils/lib/src/blockchain_lifecycle.js:3:12)
      at BlockchainLifecycle.startAsync (node_modules/@0x/dev-utils/lib/src/blockchain_lifecycle.js:53:16)
      at Context.before (dist/test/meta_fill_order.js:56:35)
```

## Possible Solution

There seems to be an extra space in the `supportedProvider.send` function signature, causing the workaround to fail:

In `provider_utils`:

```javascript
        else if (supportedProvider.send !== undefined) {
            // console.log(supportedProvider.send)
            // HACK(fabio): Detect if the `send` method has the old interface `send(payload, cb)` such
            // as in versions < Web3.js@1.0.0-beta.37. If so, do a simple re-mapping
            console.log(supportedProvider.send.toString())
            console.log('function (payload, callback)')
            console.log(_.includes(supportedProvider.send.toString(), 'function (payload, callback)'))
            if (_.includes(supportedProvider.send.toString(), 'function (payload, callback)')) {
                provider.sendAsync = supportedProvider.send.bind(supportedProvider);
                return provider;
            }
            else {
                // If doesn't have old interface, we assume it has new interface `send(method, payload)`
                // such as in versions > Web3.js@1.0.0-beta.38 and convert it to `sendAsync`
                provider.sendAsync = function (payload, callback) {
                    var method = payload.method;
                    // console.log(method)
                    var params = payload.params;
                    // console.log(params)
                    // console.log(supportedProvider.send.toString())
                    // console.log(supportedProvider.send(method, params))
                    supportedProvider
                        .send(method, params)
                        .then(function (result) {
                        callback(null, result);
                    })
                        .catch(function (err) {
                        callback(err);
                    });
                };
                return provider;
            }
        }
```

Output:

```
function(payload, callback) {
      payload = preHook(payload);

      originalSend(payload, function(error, result) {
        var modified = postHook(payload, error, result);
        payload = modified[0];
        error = modified[1];
        result = modified[2];

        callback(error, result);
      });
    }
function (payload, callback)
false
```

As you can see there is an extra space "function(payload,callback)" vs "function (payload,callback)". I believe `web@1.2.1` is using the code from <= beta37.

If I change to "function(payload, callback)", the issue goes away. 

## Steps to Reproduce (for bugs)

```
1.
2.
3.
```

## Context

Trying to get typescript to work with 0x dev utils (using BlockchainLifecycle to manage timing) and the newest version of truffle/web3

## Your Environment

| Package | Version |
| ------: | :------ |

| Network |
| ------- |
| NAME    |

**Comment by fabioberger** [comment]
Thanks for submitting! I'd be willing to accept a PR that checks for both variants (with and without the space):

```
const functionSignature = supportedProvider.send.toString();
if (_.includes(functionSignature, 'function (payload, callback)') ||
    _.includes(functionSignature, 'function(payload, callback)')) {
```

**Comment by fabioberger** [comment]
Lastly, do you mind adding an entry in the `utils` package's CHANGELOG.json file that describes this bug fix?

**Comment by xlab** [comment]
Hi @fabioberger. This issue still exists and causing major time loss among many developers trying to figure out wtf is happening in third-party pkgs :)

Another fix would be
```
if (_.includes(supportedProvider.send.toString().replace(" ", ""), 'function(payload,callback)'))
```

**Comment by mrwillis** [comment]
Still actually having issues with this. It seems it has changed to `function (payload, callback)` (note the two spaces - `replace` only replaces the first one)

**Comment by xlab** [comment]
Oh lol

**Comment by mrwillis** [comment]
@dekz Would it be possible to fix this up again and re-open this isue?
