### ISSUE TITLE
general: Error: Specified signerAddress isn't available through the supplied web3 provider

### ISSUE THREAD

**Issue by travs** [0xProject/0x-monorepo#2371]
I want to sign an order on a local ganache chain, but I get an error saying that the account is not available (though it appears to be).

Error is from `order-utils`, or at least indirectly.

## Steps to Reproduce

```js
// sample.js

const Web3 = require('web3');
const { generatePseudoRandomSalt, assetDataUtils, orderHashUtils, signatureUtils } = require('@0x/order-utils');

const main = async () => {
  const web3 = new Web3('http://localhost:8545');
  const EMPTY_ADDRESS = "0x0000000000000000000000000000000000000000";
  const deployer = '0xC0c82081f2Ad248391cd1483ae211d56c280887a';
  const exchangeAddress = '0x8C27d8cB1633C2990Ec0DA17B00CEdE3C17BBdC6';
  const someAddress1 = '0x697D686207b035AFef108F39d6aB2fe0a5528c81';
  const someAddress2 = '0xbE1aC5962e318D0335b8d8AAbFF55DC4bAd01826';
  const someAddress3 = '0x94b76e27c0caf9db8a64b6b86c8dd1d89e21d709';
  const someAddress4 = '0x834cd847a5ce0bac0eda3355df9bf9fe2420e339';

  const order = {
    exchangeAddress: exchangeAddress.toLowerCase(),
    makerAddress: someAddress3,
    takerAddress: EMPTY_ADDRESS,
    senderAddress: EMPTY_ADDRESS,
    feeRecipientAddress: EMPTY_ADDRESS,
    expirationTimeSeconds: 9999999999999999999,
    salt: generatePseudoRandomSalt().toString().slice(0, 10),
    makerAssetAmount: 1000000000,
    takerAssetAmount: 1000000000,
    makerAssetData: assetDataUtils.encodeERC20AssetData(someAddress1),
    takerAssetData: assetDataUtils.encodeERC20AssetData(someAddress2),
    makerFee: '0',
    takerFee: '0'
  };

  console.log(await web3.eth.currentProvider.send('eth_accounts'));

  const signedOrder = await signatureUtils.ecSignOrderAsync(
    web3.eth.currentProvider,
    order,
    deployer,
  );
}

main()
  .then(r => { console.log('Done'); process.exit() })
  .catch(e => { console.error(e); process.exit(1) });
```

```
$ node sample.js
[ '0xc0c82081f2ad248391cd1483ae211d56c280887a',
  '0x697d686207b035afef108f39d6ab2fe0a5528c81',
  '0x957e5117873b7e64ae9bb3d7f7e907f46de480f6',
  '0x603b6ff5667ea0610122ff483a540aa60f18d545',
  '0x83a422230f49ce9ab2d8e75c3d493a6ccf91e36a',
  '0x1141caf50b083e21bb48130460ce11eb47758545',
  '0x6029bce8e8c9fe26bc096b45b1106ff4da3eba5d',
  '0x94b76e27c0caf9db8a64b6b86c8dd1d89e21d709',
  '0x834cd847a5ce0bac0eda3355df9bf9fe2420e339',
  '0xbe1ac5962e318d0335b8d8aabff55dc4bad01826' ]
Error: Specified signerAddress 0xC0c82081f2Ad248391cd1483ae211d56c280887a isn't available through the supplied web3 provider
    at Object.assert (node_modules/@0x/assert/lib/src/index.js:99:19)
    at Object.<anonymous> (node_modules/@0x/order-utils/lib/src/assert.js:63:41)
    at step (node_modules/@0x/order-utils/lib/src/assert.js:43:23)
    at Object.next (node_modules/@0x/order-utils/lib/src/assert.js:24:53)
    at fulfilled (node_modules/@0x/order-utils/lib/src/assert.js:15:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Environment

| Package | Version |
| ------: | :------ |
| web3 | 2.0.0-alpha.1 |
| @0x/order-utils | 8.4.0 |

Ganache local devchain
```
Ganache CLI v6.7.0 (ganache-core: 2.8.0)
```

**Comment by dekz** [comment]
Looks like one of our tools isn't lower casing your input address. To work around this currently you can `const deployer = '0xC0c82081f2Ad248391cd1483ae211d56c280887a'.toLowerCase();`

**Comment by deacix** [comment]
toLowerCase is not helping..
