### ISSUE TITLE
@0xproject/base-contract not found

### ISSUE THREAD

**Issue by Xaber20110202** [0xProject/0x-monorepo#435]
When I yarn add 0x.js, there was an error

```
An unexpected error occurred: "http://registry.npmjs.org/@0xproject%2fbase-contract: Not found".
```

https://www.npmjs.com/package/@0xproject/base-contract

**Comment by LogvinovLeon** [comment]
It's probably the problem with our latest release. I'll try to fix that ASAP. In the meanwhile - feel free to use the previous version

**Comment by LogvinovLeon** [comment]
Hmm. Just tried to reproduce on an empty repo and it worked for me. Also - the package seems to be there. Could you please try to give more details? Logs/versions/steps?

**Comment by Xaber20110202** [comment]
Hi, I tried add package in a new project, but still not work, my error log was that,

```
Arguments: 
  /Users/Xaber/.nvm/versions/node/v9.3.0/bin/node /usr/local/bin/yarn add 0x.js@0.33

PATH: 
  /Users/Xaber/.nvm/versions/node/v9.3.0/bin:/Users/Xaber/Workspaces/shell:/Users/Xaber/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/bin:/Users/Xaber/Workspaces/hxdev/java tool/apache-maven-3.3.9/bin:/Users/Xaber/Workspaces/Xaber/phantomjs-2.1.1-macosx/bin/

Yarn version: 
  0.18.1

Node version: 
  9.3.0

Platform: 
  darwin x64

npm manifest: 
  {
    "name": "test",
    "version": "1.0.0",
    "main": "index.js",
    "license": "MIT"
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: http://registry.npmjs.org/@0xproject%2fbase-contract: Not found
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/0.18.1/libexec/lib/node_modules/yarn/lib/util/request-manager.js:309:18)
      at Request.self.callback (/usr/local/Cellar/yarn/0.18.1/libexec/lib/node_modules/yarn/node_modules/request/request.js:186:22)
      at Request.emit (events.js:159:13)
      at Request.<anonymous> (/usr/local/Cellar/yarn/0.18.1/libexec/lib/node_modules/yarn/node_modules/request/request.js:1081:10)
      at Request.emit (events.js:159:13)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/0.18.1/libexec/lib/node_modules/yarn/node_modules/request/request.js:1001:12)
      at Object.onceWrapper (events.js:254:19)
      at IncomingMessage.emit (events.js:164:20)
      at endReadableNT (_stream_readable.js:1062:12)
      at process._tickCallback (internal/process/next_tick.js:152:19)

```

**Comment by Xaber20110202** [comment]
I think it's probably you didn't publish @0xproject/base-contract to npm

**Comment by LogvinovLeon** [comment]
Looks like it was accidentally published as private. just made it public. Might take some time to propagate. Is still cached for me.

**Comment by Xaber20110202** [comment]
It works, thank you 😄

**Comment by LogvinovLeon** [comment]
Thanks for reporting. Appologies for the inconvenience.
