### ISSUE TITLE
0x.js not working with HDWalletSubprovider

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-monorepo#439]
## Expected Behavior

Should be able to use HDWalletSubprovider  with 0x.js.

## Current Behavior

Doesn't work. Error says `INVALID_SIGNATURE`.

Source code:

```
var HDWalletProvider = require("truffle-hdwallet-provider");
var provider = new HDWalletProvider(mnemonic, "https://mainnet.infura.io/yXDUNwlNOcx0UJCWjzNr");
var configs = {
    networkId: 1,
};
var zeroEx = new ZeroEx(provider, configs);

const WETH_ADDRESS = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2";
const MKR_ADDRESS = "0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2";
const feeRecipient = "0xa258b39954cef5cb142fd567a46cddb31a670124";
const EXCHANGE_ADDRESS = zeroEx.exchange.getContractAddress();

const order = {
    maker: makerAddress,
    taker: ZeroEx.NULL_ADDRESS,
    feeRecipient: ZeroEx.NULL_ADDRESS,
    makerTokenAddress: WETH_ADDRESS,
    takerTokenAddress: MKR_ADDRESS,
    exchangeContractAddress: EXCHANGE_ADDRESS,
    salt: ZeroEx.generatePseudoRandomSalt(),
    makerFee: new BigNumber(0),
    takerFee: new BigNumber(0),
    makerTokenAmount: ZeroEx.toBaseUnitAmount(new BigNumber(0.005), DECIMALS), // Base 18 decimals
    takerTokenAmount: ZeroEx.toBaseUnitAmount(new BigNumber(0.00431), DECIMALS), // Base 18 decimals
    expirationUnixTimestampSec: new BigNumber(Date.now() + 3600000), // Valid for up to an hour
};

const orderHash = ZeroEx.getOrderHashHex(order);
const shouldAddPersonalMessagePrefix = false;
const ecSignature = await zeroEx.signOrderHashAsync(orderHash, makerAddress, shouldAddPersonalMessagePrefix);
```

Error:

```
Caught error: Error: INVALID_SIGNATURE at ZeroEx.<anonymous> (C:\Users\xunzheng\source\repos\radarTs\radarTs\node_modules\0x.js\lib\src\0x.js:277:31) at step (C:\Users\xunzheng\source\repos\radarTs\radarTs\node_modules\0x.js\lib\src\0x.js:46:23) at Object.next (C:\Users\xunzheng\source\repos\radarTs\radarTs\node_modules\0x.js\lib\src\0x.js:27:53) at fulfilled (C:\Users\xunzheng\source\repos\radarTs\radarTs\node_modules\0x.js\lib\src\0x.js:18:58) at <anonymous>
```

## Possible Solution

Add both message prefix and hashing in `HookedWalletEthTxSubprovider`.

**Comment by fabioberger** [comment]
If you are trying to use the Truffle HDWalletProvider with 0x.js, make sure to use this fork: https://github.com/0xProject/truffle-hdwallet-provider until this PR is merged to the original repo: https://github.com/trufflesuite/truffle-hdwallet-provider/pull/22.
