### ISSUE TITLE
Arbitrage Contract : running the test

### ISSUE THREAD

**Issue by JGdBB** [0xProject/0x-monorepo#481]
I have followed all the instruction to set up the test :
- yarn config set workspaces-experimental true
- yarn install
- yarn build
- yarn lint

## Expected Behavior

yarn test => run the test

## Current Behavior

ReferenceError: ProviderEngine is not defined
    at Object.getRpcProvider (/home/ethereum/0x-monorepo/packages/dev-utils/lib/src/web3_factory.js:18:24)
    at Object.create (/home/ethereum/0x-monorepo/packages/dev-utils/lib/src/web3_factory.js:11:29)
    at Object.<anonymous> (/home/ethereum/0x-monorepo/packages/contracts/lib/test/utils/web3_wrapper.js:6:40)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ethereum/0x-monorepo/packages/contracts/lib/test/utils/deployer.js:7:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ethereum/0x-monorepo/packages/contracts/lib/test/ether_token.js:46:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/ethereum/0x-monorepo/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/ethereum/0x-monorepo/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/home/ethereum/0x-monorepo/node_modules/mocha/lib/mocha.js:536:10)
    at Object.<anonymous> (/home/ethereum/0x-monorepo/node_modules/mocha/bin/_mocha:573:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
error An unexpected error occurred: "Command failed.
Exit code: 7
Command: sh
Arguments: -c mocha 'lib/test/**/*.js' --timeout 100000 --bail --exit
Directory: /home/ethereum/0x-monorepo/packages/contracts
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/ethereum/0x-monorepo/packages/contracts/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "run_mocha" exited with 1.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c run-s build run_mocha
Directory: /home/ethereum/0x-monorepo/packages/contracts
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/ethereum/0x-monorepo/packages/contracts/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

##Thanks for your help !

**Comment by fabioberger** [comment]
@JGdBB are you running this in the mono repo?

If so, install and build all the packages by running:

```
yarn
```

and then

```
yarn lerna:rebuild
```

From the top-level monorepo directory. 

Can you let me know if that helped?

**Comment by JGdBB** [comment]
It works. 
Thanks !
