### ISSUE TITLE
dependent web3 version results in Error: Cannot find module 'web3-requestManager'` 

### ISSUE THREAD

**Issue by Andersmholmgren** [0xProject/0x-monorepo#565]
## Expected Behavior

I have code that imports the following

```
import Web3ProviderEngine = require('web3-provider-engine');
import RpcSubprovider = require('web3-provider-engine/subproviders/rpc');

import { PrivateKeyWalletSubprovider } from '@0xproject/subproviders';
import { Web3Wrapper } from '@0xproject/web3-wrapper';
import { ZeroEx } from '0x.js';

```

with dependencies

```
"dependencies": {
    "0x.js": "^0.36.3",
    "@0xproject/connect": "^0.6.10",
    "@0xproject/subproviders": "^0.9.0",
   ... lots of others
},
"devDependencies": {
    "@0xproject/types": "^0.6.1",
   ... lots of others
}

```
The code should be able to resolve the 'web3-requestManager' module

## Current Behavior

I get the following exception trying to run the code. The stack trace is not super helpful in illuminating the exact location

```
Error: Cannot find module 'web3-requestManager'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/blah/myproject/node_modules/ganache-core/node_modules/web3/packages/web3-core/src/index.js:26:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

## Possible Solution
Adding
```
  "resolutions": {
    "web3": "^1.0.0-beta.34"
  }
```
to package.json works around the issue

**Comment by fabioberger** [comment]
Removed web3.js from our libraries.
