### ISSUE TITLE
can not init ZeroEx instance

### ISSUE THREAD

**Issue by helxsz** [0xProject/0x-monorepo#606]
I am using the 0x.js on the node server, the code is 

```
var Web3 = require('web3');
var ZeroEx = require('0x.js').ZeroEx;
var web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
console.log(web3.currentProvider);
var zeroEx = new ZeroEx(web3.currentProvider);

```
## Current Behavior

```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at SchemaValidator.validate (/Users/xisizhe/Documents/projects/decentralized_exchange/node_modules/@0xproject/json-schemas/lib/src/schema_validator.js:40:47)
    at Object.doesConformToSchema (/Users/xisizhe/Documents/projects/decentralized_exchange/node_modules/@0xproject/assert/lib/src/index.js:58:48)
    at new ZeroEx (/Users/xisizhe/Documents/projects/decentralized_exchange/node_modules/0x.js/lib/src/0x.js:68:25)
    at Object.<anonymous> (/Users/xisizhe/Documents/projects/decentralized_exchange/modules/0xrelay/server/controller/exchange.controller.js:21:14)
    at Module._compile (module.js:643:30)
```

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|            0x@4.0.11
             0x.js@0.37.2
| `Exchange Contract` | v1      |

| Network |
| ------- |
| NAME    |

**Comment by imbaniac** [comment]
You should specify networkId as the second parameter. For example for mainnet:

`
const zeroEx = new ZeroEx(web3.currentProvider, {
  networkId: 1
});
`

**Comment by helxsz** [comment]
that is right, thank you.
