### ISSUE TITLE
TypeError: Cannot read property 'inputs' of undefined

### ISSUE THREAD

**Issue by tantao9323** [0xProject/0x-monorepo#680]
## Expected Behavior

I try to use `fillOrderAsync` to fill an order, it should return a txHash.

## Current Behavior

It throws an error `TypeError: Cannot read property 'inputs' of undefined`.
Below is detail:
 
`at ExchangeContract.<anonymous> (/Users/tantao/Projects/tx-test/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/generated/exchange.js:887:37)
    at step (/Users/tantao/Projects/tx-test/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/generated/exchange.js:50:23)
    at Object.next (/Users/tantao/Projects/tx-test/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/generated/exchange.js:31:53)
    at /Users/tantao/Projects/tx-test/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/generated/exchange.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/tantao/Projects/tx-test/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/generated/exchange.js:21:12)
    at ExchangeContract.estimateGasAsync (/Users/tantao/Projects/tx-test/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/generated/exchange.js:879:24)
    at Function.<anonymous> (/Users/tantao/Projects/tx-test/node_modules/@0xproject/base-contract/lib/src/index.js:105:46)
    at step (/Users/tantao/Projects/tx-test/node_modules/@0xproject/base-contract/lib/src/index.js:40:23)
    at Object.next (/Users/tantao/Projects/tx-test/node_modules/@0xproject/base-contract/lib/src/index.js:21:53)
    at /Users/tantao/Projects/tx-test/node_modules/@0xproject/base-contract/lib/src/index.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/tantao/Projects/tx-test/node_modules/@0xproject/base-contract/lib/src/index.js:11:12)
    at Function.BaseContract._applyDefaultsToTxDataAsync (/Users/tantao/Projects/tx-test/node_modules/@0xproject/base-contract/lib/src/index.js:97:16)
    at ExchangeContract.<anonymous> (/Users/tantao/Projects/tx-test/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/generated/exchange.js:866:83)
    at step (/Users/tantao/Projects/tx-test/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/generated/exchange.js:50:23)
    at Object.next (/Users/tantao/Projects/tx-test/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/generated/exchange.js:31:53)
    at /Users/tantao/Projects/tx-test/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/generated/exchange.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/tantao/Projects/tx-test/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/generated/exchange.js:21:12)
    at ExchangeContract.sendTransactionAsync (/Users/tantao/Projects/tx-test/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/generated/exchange.js:846:24)
    at ExchangeWrapper.<anonymous> (/Users/tantao/Projects/tx-test/node_modules/@0xproject/contract-wrappers/lib/src/contract_wrappers/exchange_wrapper.js:229:73)`

## Possible Solution

I locate `inputAbi = self._lookupAbi('fillOrder(address[5],uint256[6],uint256,bool,uint8,bytes32,bytes32)').inputs;`. It can‘t seems to get the exchangeContract's abi.

## Your Environment

|             Package | Version |
| ------------------: | :------ |
|             `0x.js` | 0.38.3  |

| Network |
| ------- |
| rinkeby    |

**Comment by fuJiin** [comment]
Also running into this issue.

**Comment by fabioberger** [comment]
@tantao9323 are you passing in the `signedOrder` with numerical values represented as BigNumbers? Please paste your `signedOrder` below.

**Comment by fabioberger** [comment]
Also, what is your networkId?

**Comment by LogvinovLeon** [comment]
Our dev power now is concentrated around migrating dev tools for v2 of the protocol. If downgrading a minor version down helps - please do that and I'll just unpublish the buggy version. If no - ping me and I'll look closer into that.

**Comment by LogvinovLeon** [comment]
This issue looks super similar to the one we've recently fixed. Could you please try to use the latest version of 0x.js and confirm that it's fixed?

**Comment by LogvinovLeon** [comment]
Please reopen if you still experience that with the last version of 0x.js published today.
