### ISSUE TITLE
Error while using `zeroEx.exchange.subscribe`: received log with same block number but index newer than previous index

### ISSUE THREAD

**Issue by mohoff** [0xProject/0x-monorepo#693]
Hi 0x team,
might have found a bug that is described below. Thanks for investigating! Looking forward to v2 :)

## Expected Behavior
Trying to listen to events emitted from `Exchange.sol` by using the 0x.js library and its `zeroEx.exchange.subscribe` method. I think it should callback every time an event is emitted.

## Current Behavior
Subscription seems successful but once the first event is received my script fails with:

```
Error: received log with same block number but index newer than previous index
    at ensureOrder (/home/mo/dev/0x-openrelay-playground/node_modules/0x.js/node_modules/ethereumjs-blockstream/output/source/log-reconciler.js:140:15)
    at /home/mo/dev/0x-openrelay-playground/node_modules/0x.js/node_modules/ethereumjs-blockstream/output/source/log-reconciler.js:91:21
    at step (/home/mo/dev/0x-openrelay-playground/node_modules/0x.js/node_modules/ethereumjs-blockstream/output/source/log-reconciler.js:32:23)
    at Object.next (/home/mo/dev/0x-openrelay-playground/node_modules/0x.js/node_modules/ethereumjs-blockstream/output/source/log-reconciler.js:13:53)
    at /home/mo/dev/0x-openrelay-playground/node_modules/0x.js/node_modules/ethereumjs-blockstream/output/source/log-reconciler.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/mo/dev/0x-openrelay-playground/node_modules/0x.js/node_modules/ethereumjs-blockstream/output/source/log-reconciler.js:3:12)
    at addNewLogsToHead (/home/mo/dev/0x-openrelay-playground/node_modules/0x.js/node_modules/ethereumjs-blockstream/output/source/log-reconciler.js:80:12)
    at Object.<anonymous> (/home/mo/dev/0x-openrelay-playground/node_modules/0x.js/node_modules/ethereumjs-blockstream/output/source/log-reconciler.js:51:42)
    at step (/home/mo/dev/0x-openrelay-playground/node_modules/0x.js/node_modules/ethereumjs-blockstream/output/source/log-reconciler.js:32:23)
    at Object.next (/home/mo/dev/0x-openrelay-playground/node_modules/0x.js/node_modules/ethereumjs-blockstream/output/source/log-reconciler.js:13:53)
    at fulfilled (/home/mo/dev/0x-openrelay-playground/node_modules/0x.js/node_modules/ethereumjs-blockstream/output/source/log-reconciler.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

## Steps to Reproduce (for bugs)
The code:
```
const eventName = 'LogFill'
const tokenPair = web3.utils.sha3(
        '0xe41d2489571d322189246dafa5ebde1f4699f498',  // ZRX contract on mainnet
        '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'   // WETH contract on mainnet
)

zeroEx.exchange.subscribe(
    eventName,
    indexFilterValues,
    async (err, decodedLogEvent) => {
        if (err) {
            console.log(err)
            return;
        } else {
            console.log(decodedLogEvent)
        }
    }
)
```

## Context

see intro

## Your Environment

|             Package | Version       |
| ------------------: | :------------ |
|             `0x.js` | 0.37.2        |
|              `web3` | 1.0.0-beta.34 |

| Network |
| ------- |
| mainnet |

**Comment by LogvinovLeon** [comment]
Seems like an [ethereumjs-blockstream](https://github.com/ethereumjs/ethereumjs-blockstream/blob/6580081619f8518c5f242262266554754ab12e3a/source/log-reconciler.ts#L63) issue to me. How ofter does that happen? Do you use infura?

**Comment by mohoff** [comment]
I get this every time I'm running my script on the first log received.
Yes, using Infura with a subprovider setup (mnemonic wallet subprovider for signing, the rest with Infura via RPC subprovider.

I opened an issue in their repo: https://github.com/ethereumjs/ethereumjs-blockstream/issues/17

**Comment by mohoff** [comment]
Apparently a duplicate of https://github.com/ethereumjs/ethereumjs-blockstream/issues/10, which you opened some time ago, @LogvinovLeon . 

So looks like `zeroEx.exchange.subscribe` doesn't work currently on any non-testrpc net.

**Comment by MicahZoltu** [comment]
I _think_ Augur setup a bounty to get Geth/Parity to fix their JSON-RPC API so this can be fixed.  I'm not sure what the status of that is though.

**Comment by MicahZoltu** [comment]
https://eips.ethereum.org/EIPS/eip-234

**Comment by MicahZoltu** [comment]
I think I have a way to fix this without Geth/Parity adding the desired RPC method.  Will try to get a new version out today.

**Comment by MicahZoltu** [comment]
I believe I have a fix ready for `ethereumjs-blockstream` that addresses this issue.  Going to wait a few days before merging and releasing though as I want to review the change after some time to forget it.  If this is something critical that needs a fix ASAP let me know and I can consider moving up the timetable.

**Comment by fabioberger** [comment]
Fixed in latest version of our libraries.
